# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Varying Vagrant Vagrants
email: jeremy.felt@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
#url: "https://varyingvagrantvagrants.org" # the base hostname & protocol for your site
markdown: kramdown
plugins: [jekyll-paginate]
permalink: /blog/:year/:month/:day/:title.html
paginate: 10
paginate_path: /blog/page:num
exclude:
  - vendor
  - README.md
  - Gemfile*
navigation:
- text: Blog
  url: /blog/
  layout: post
- text: Documentation
  url: /docs/en-US/
